#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Roman
Version  : 3.5
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/S/SY/SYP/Text-Roman-3.5.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SY/SYP/Text-Roman-3.5.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtext-roman-perl/libtext-roman-perl_3.5-2.debian.tar.xz
Summary  : 'Allows conversion between Roman and Arabic algarisms.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Text-Roman-license
Requires: perl-Text-Roman-man

%description
NAME
Text::Roman - Allows conversion between Roman and Arabic algarisms.
VERSION
version 3.5

%package license
Summary: license components for the perl-Text-Roman package.
Group: Default

%description license
license components for the perl-Text-Roman package.


%package man
Summary: man components for the perl-Text-Roman package.
Group: Default

%description man
man components for the perl-Text-Roman package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Text-Roman-3.5
mkdir -p %{_topdir}/BUILD/Text-Roman-3.5/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Text-Roman-3.5/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Text-Roman
cp LICENSE %{buildroot}/usr/share/doc/perl-Text-Roman/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/Roman.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Text-Roman/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Text::Roman.3
